VIDEO:
  MODE: "webcam"  # webcam, video
  VIDEO_PATH: "src/data/data/datasample_video.mp4"
  WEBCAM_ID: 0  # Change webcam ID if needed

DISPLAY:
  FPS: false  # Show only FPS
  VERBOSE: false
  OVERLAY_COLOR: [ 255, 0, 0 ]  # Red overlay text
  EMOJI: false

MODEL: { }

LOGGING:
  SAVE_TO_FILE: false
  LOG_FILE: "logs/output.log"

DATASET:
  PATH: "src/data/data"

TRAIN:
  BATCH_SIZE: 128
  LR: 0.001
  EPOCHS: 50
  MODEL_NAME: "efficientnet_b0"

EXPORT:
  ENABLED: true
  EVAL: true
  MODEL_NAME: "efficientnet_b0"
  INPUT_WEIGHTS: "src/models/weights/efficientnet_b0_fer.pth"
  OUTPUT_PATH: "src/models/weights/EfficientNetFER.onnx"

INFERENCE:
  CONFIDENCE_THRESHOLD: 0.5
  YOLO_PATH: "src/models/weights/yolov11n-face.onnx"
  FER_PATH: "src/models/weights/EfficientNetFER.onnx"
  YOLO_DOWNLOAD_URL: "https://github.com/akanametov/yolo-face/releases/download/v0.0.0/yolov11n-face.onnx"
  FER_DOWNLOAD_URL: "https://drive.google.com/uc?export=download&id=1tT8sjm-09ppD-CCzLu0zp8eSjQ37tsjH"

API:
  HOST: "0.0.0.0"
  PORT: 8000
  CORS_ORIGINS: [ "*" ]
  MAX_VIDEO_SIZE_MB: 100
  MAX_IMAGE_SIZE_MB: 10
  ALLOWED_VIDEO_EXT: [ ".mp4", ".avi", ".mov" ]
  ALLOWED_IMAGE_EXT: [ ".jpg", ".jpeg", ".png" ]

IS_TRAINING: true
