name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: orbital-signal-467013-i4
  REGION: asia-south1
  SERVICE: fer-app
  WORKLOAD_IDENTITY_PROVIDER: projects/216714448776/locations/global/workloadIdentityPools/github-actions-prod/providers/github-actions-provider
  SERVICE_ACCOUNT: ci-cd-sa@orbital-signal-467013-i4.iam.gserviceaccount.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Docker Auth
        run: gcloud auth configure-docker "${{ env.REGION }}-docker.pkg.dev"

      - name: Build and Push Container
        run: |
          IMAGE_URI="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}"
          docker build -t "${IMAGE_URI}" .
          docker push "${IMAGE_URI}"

      - id: deploy
        name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}"
          flags: |
            --allow-unauthenticated   # optional
            # --service-account=another-sa@${{ env.PROJECT_ID }}.iam.gserviceaccount.com

      - name: Show output
        run: |2-
          echo "Deployed URL: ${{ steps.deploy.outputs.url }}"
